//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmellFinderTool.Resources {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings_en_US {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings_en_US() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("SmellFinderTool.Resources.Strings_en_US", typeof(Strings_en_US).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string askDirectoryName {
            get {
                return ResourceManager.GetString("askDirectoryName", resourceCulture);
            }
        }
        
        internal static string askSmellToValidate {
            get {
                return ResourceManager.GetString("askSmellToValidate", resourceCulture);
            }
        }
        
        internal static string menuChoiceText {
            get {
                return ResourceManager.GetString("menuChoiceText", resourceCulture);
            }
        }
        
        internal static string all {
            get {
                return ResourceManager.GetString("all", resourceCulture);
            }
        }
        
        internal static string warn {
            get {
                return ResourceManager.GetString("warn", resourceCulture);
            }
        }
        
        internal static string error {
            get {
                return ResourceManager.GetString("error", resourceCulture);
            }
        }
        
        internal static string success {
            get {
                return ResourceManager.GetString("success", resourceCulture);
            }
        }
        
        internal static string selectOption {
            get {
                return ResourceManager.GetString("selectOption", resourceCulture);
            }
        }
        
        internal static string progress {
            get {
                return ResourceManager.GetString("progress", resourceCulture);
            }
        }
        
        internal static string notFoundFile {
            get {
                return ResourceManager.GetString("notFoundFile", resourceCulture);
            }
        }
        
        internal static string numberOfFile {
            get {
                return ResourceManager.GetString("numberOfFile", resourceCulture);
            }
        }
        
        internal static string okResult {
            get {
                return ResourceManager.GetString("okResult", resourceCulture);
            }
        }
        
        internal static string chooseExtensionFile {
            get {
                return ResourceManager.GetString("chooseExtensionFile", resourceCulture);
            }
        }
        
        internal static string outputFileExtensionSelected {
            get {
                return ResourceManager.GetString("outputFileExtensionSelected", resourceCulture);
            }
        }
        
        internal static string optionsSelected {
            get {
                return ResourceManager.GetString("optionsSelected", resourceCulture);
            }
        }
        
        internal static string reprocess {
            get {
                return ResourceManager.GetString("reprocess", resourceCulture);
            }
        }
        
        internal static string smellsInstructions {
            get {
                return ResourceManager.GetString("smellsInstructions", resourceCulture);
            }
        }
        
        internal static string selectorKey {
            get {
                return ResourceManager.GetString("selectorKey", resourceCulture);
            }
        }
        
        internal static string continueKey {
            get {
                return ResourceManager.GetString("continueKey", resourceCulture);
            }
        }
        
        internal static string yes {
            get {
                return ResourceManager.GetString("yes", resourceCulture);
            }
        }
        
        internal static string no {
            get {
                return ResourceManager.GetString("no", resourceCulture);
            }
        }
    }
}
